# ansible deploy web app
---
- name: deploy web app
  hosts: n2
  become: yes

  tasks:
  - name: Install Git
    yum:
     name: git
     state: present
     
  - name: Host Code
    git:
     repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
     dest: /var/www/html
     force: yes
    register: git_result

  - name: Debugging - Git task result
    debug:
      var: git_result

  - name: Restart Apache
    service:
      name: httpd
      state: restarted

...
