---
- name: Install HTTP server
  hosts: all
  become: yes

  tasks:
    - name: Install HTTPD
      package:
        name: "{{ 'httpd' if ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS' else 'apache2' }}"
        state: present
      when: ansible_distribution in ['Amazon', 'CentOS', 'Ubuntu', 'Debian']

    - name: Start HTTPD or Apache2
      service:
        name: "{{ 'httpd' if ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS' else 'apache2' }}"
        state: started
      when: ansible_distribution in ['Amazon', 'CentOS', 'Ubuntu', 'Debian']

    - name: Enable HTTPD or Apache2
      service:
        name: "{{ 'httpd' if ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS' else 'apache2' }}"
        enabled: yes
      when: ansible_distribution in ['Amazon', 'CentOS', 'Ubuntu', 'Debian']
...