#Install HTTP
---
- name: Install HTTP server
  hosts: all
  become: yes

  tasks:
  - name: Install dnf on CentOS/Amazon
    raw: "sudo yum install -y dnf"
    when: ansible_distribution == ['Amazon', 'CentOS']

  - name: Install HTTPD on CentOS/Amazon
    dnf:
     name: httpd
     state: present
    when: ansible_distribution == ['Amazon', 'CentOS']

  - name: Start httpd on CentOS/Amazon
    service:
     name: httpd
     state: started
    when: ansible_distribution == ['Amazon', 'CentOS']

  - name: Enable httpd on CentOS/Amazon
    service:
     name: httpd
     enabled: yes
    when: ansible_distribution == ['Amazon', 'CentOS']

  - name: Install Apache2 on Ubuntu/Debian
    apt:
     name: apache2
     state: present
    when: ansible_distribution == ['Ubuntu', 'Debian']

  - name: Start apache2 on Ubuntu/Debian
    service:
     name: apache2
     state: started
    when: ansible_distribution == ['Ubuntu', 'Debian']

  - name: Enable apache2 on Ubuntu/Debian
    service:
     name: apache2
     enabled: yes
    when: ansible_distribution == ['Ubuntu', 'Debian']
...